### ISSUE TITLE
feature request: integrate with fzf  & jump to dir

### ISSUE THREAD

**Issue by Dentrax** [nickgerace/gfold#168]
Thanks for such a great tool!

---

Currently, it's a bit hard to use without _selective_ mode. I still want to use fzf git repo search and jumping to dir by pressing <kbd>ENTER</kbd>.

[atuin](https://github.com/ellie/atuin) would be a great benchmark for this feature.

![Screen Shot 2022-01-12 at 15 13 13](https://user-images.githubusercontent.com/16493751/149138271-15d3b7e1-1d13-45ff-97f2-d5f6e33aa224.png)

What do you think?

**Comment by nickgerace** [comment]
Thank you! I want to make sure that I understand the request:

Are you saying that you would like to jump to a directory with the given list of results? Perhaps in a TUI mode?

Although the performance of finding `git` repos can be improved, I am unsure what `fzf` integration will provide here. We will already have the results for all the repositories by the time you want to "jump", so `fzf` might not help by that point.

That being said, I could see a minimal TUI integration where you highlight a result, click "ENTER" on your keyboard, and then your current working directory is changed to it.

**Comment by Dentrax** [comment]
> Are you saying that you would like to jump to a directory with the given list of results?

Yes! I thought _fzf_ would just enough to handle jumping or searching, but you mentioned "fzf might not help". So, how `atuin` handles this?

**Comment by nickgerace** [comment]
From what I understand, `atuin` uses `fzf` for its search. `gfold` has its own search. While `fzf` is amazing, I think the main request here is to be able to `cd` into a repository via TUI. `fzf` may or may not replace `gfold`'s search in this scenario, but that'll be done when researching this feature request.

Thus, I think it may be best to focus on the request to add an interactive mode where you can jump to a directory in the results. Whether or not `fzf` is involved can would likely be decided during the research phase :)

**Comment by mriehl** [comment]
If you want to jump to dir you need to eval it on the shell side. We have it in [fw](https://github.com/brocode/fw) (which you also could consider using :wink: )

**Comment by nickgerace** [comment]
> If you want to jump to dir you need to eval it on the shell side. We have it in [fw](https://github.com/brocode/fw) (which you also could consider using wink ). The idea is heavily inspired by virtualenvwrapper with the `workon` command, of course.

This is what I have found from preliminary research as well. I'm still evaluating if it makes sense for this project, but I believe there is likely a path forward that doesn't stray too far from the core design.

**Comment by BerkeleyTrue** [comment]
For those interested, I've integrated this project into a script that allows me to jump through projects while opening them in new Tmux sessions. 

You can achieve the above requirements using some simple scripts. I know the issue is about direct integration into this cli but I figured this can get you there in the meantime.

```bash
  res=$(
    gfold $dir |
      awk 'NR%4==1' |
      sed 's/\x1b\[[0-9;]*m//g' |
      fzf --reverse --header="Select project" --prompt=">" || exit 0
  )
```
Notes:
* $dir being the directory you want to search. 
* `awk 'NR%4==1` will skip to the write rows of output from gfold to grab the project directory. (`line number` modulo 4 is equal to 1)
* I've completely forgotten why the sed line was necessary 
* the fzf command is just formatting

It looks like this: 

![image](https://user-images.githubusercontent.com/6775919/167981557-7d598deb-8870-45e1-a261-7ab60c09df16.png)

The output should be the  directory you want to `cd` into (full path) plus the project name. You'll need to parse out that bit. You can do that with this line `path_name=$(echo $res | awk -F ' ~ ' '{print $2}')`

The full script can be found here (with focus on the relevant lines for this conversion: 
https://github.com/berkeleytrue/dotfiles/blob/master/.local/bin/ta#L154



Hope y'all find this useful.

**Comment by nickgerace** [comment]
Thank you @BerkeleyTrue for the workaround for now! It looks great. I wonder: would the new `json` output help here? It might be easier to parse.

**Comment by BerkeleyTrue** [comment]
@nickgerace Yes, that would make integrating this project into others scripts much easier.

I also just remembered what the sed command is for, it's to remove the color escape terms, which where causing issues downstream. Tt would be helpful to add a no color option as well.

**Comment by nickgerace** [comment]
You are in luck! There is a no color option. Here's both together:

```shell
gfold -d json -c never
```

And you can dump those options into a config file to override defaults...

```bash
gfold -d json -c never --dry-run > ~/.config/gfold.toml
```

**Comment by nickgerace** [comment]
I commented on #169 as well ([link](https://github.com/nickgerace/gfold/issues/169#issuecomment-2206402654)), but `gfold` has settled on being a non-interactive, one-time use tool.

_However_, @BerkeleyTrue if you are still using this tool in a similar capacity, I highly recommend trying it out with the `json` display output and the color output disabled. We can likely add a section in `README.md` or somewhere in the docs with your `fzf` integration steps.
